title: "Abhinav's Personal Blog"
description: "Exploring Tech, Mathematics, Music, Travel, and Carpentry"
baseurl: "" # for user/username.github.io repo, else "/repo-name"
url: "https://kmrabhinav.github.io"
theme: minima
permalink: /:categories/:title/
collections:
  tech:
    output: true
  mathematics:
    output: true
  music:
    output: true
  travel:
    output: true
  carpentry:
    output: true